# Kickstart file automatically generated by anaconda.
install
url --url ftp://ftp.iitb.ac.in/opensource/distributions/centos/5.4/os/x86_64
lang en_US.UTF-8
keyboard us
network --device eth4 --bootproto static --ip 10.101.1.4 --netmask 255.255.0.0 --gateway 10.101.250.1 --nameserver 10.101.1.2,10.101.1.1 --hostname lock.aero.iitb.ac.in
network --device eth1 --onboot no --bootproto dhcp --hostname lock.aero.iitb.ac.in
network --device eth2 --onboot no --bootproto dhcp --hostname lock.aero.iitb.ac.in
network --device eth3 --onboot no --bootproto dhcp --hostname lock.aero.iitb.ac.in
network --device eth0 --onboot no --bootproto dhcp --hostname lock.aero.iitb.ac.in
network --device eth5 --onboot no --bootproto dhcp --hostname lock.aero.iitb.ac.in
rootpw --iscrypted $1$R0z8h.Ta$EVwCcNyJqPaWKPlwCLfkP.
firewall --enabled --port=22:tcp
authconfig --enableshadow --enablemd5
selinux --enforcing
timezone Asia/Kolkata
bootloader --location=mbr --driveorder=sda
# The following is the partition information you requested
# Note that any partitions you deleted are not expressed
# here so unless you clear all partitions first, this is
# not guaranteed to work
clearpart --all
part / --fstype ext3 --size=200000 --asprimary
part /opt --fstype ext3 --size=300000 --asprimary
part swap --size=30000
part /home --fstype ext3 --size=100 --grow
#clearpart --linux
#part / --fstype ext3 --size=200000 --asprimary
#part /opt --fstype ext3 --size=300000 --asprimary
#part swap --size=30000
#part /home --fstype ext3 --size=100 --grow

%packages
@base
@core
@editors
@hindi-support
@legacy-software-support
@text-internet
keyutils
trousers
fipscheck
device-mapper-multipath
cpufreq-utils
-sendmail
-bluez-utils
